swayimg.slideshow.set_timeout(10)      
swayimg.imagelist.set_order("random")
swayimg.on_window_resize(function()
  swayimg.slideshow.set_fix_scale("fit")
end)
swayimg.slideshow.set_default_scale("fit")
swayimg.text.hide(true)
swayimg.slideshow.on_key("Left", function()
  swayimg.slideshow.switch_image("prev")
end)
swayimg.slideshow.on_key("Right", function()
  swayimg.slideshow.switch_image("next")
end)
