notify = true
shuffle = true

[theme]
background = "#"
primary = "#BBBBBB"
secondary = "#444444"
title = "EEEEEE"
playing = "#EEEEEE"
playing_selected = "#EEEEEE"
playing_bg = "#888888"
highlight = "#EEEEEE"
highlight_bg = "#666666"
error = "#000000"
error_bg = "#FF0000"
statusbar = "#EEEEEE"
statusbar_progress = "#888888"
statusbar_bg = "#222222"
cmdline = "#EEEEEE"
cmdline_bg = "#222222"
search_match = "#FF0000"

[configuration]
hide_display_names = true
